apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitor-system
spec:
  values: 
    vmcluster:
      enabled: true
      spec:
        retentionPeriod: "2"
        replicationFactor: 2
        vmstorage:
          replicaCount: 2
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
        vmselect:
          replicaCount: 2
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
        vminsert:
          replicaCount: 2
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
      ingress:
        storage:
          hosts:
            - vmstorage.example.com
        select:
          hosts:
            - vmselect.example.com
        insert:
          hosts:
            - vminsert.example.com
    vmagent:
      ingress:
        hosts:
        - vmagent.example.com
      spec:
        externalLabels:
          cluster: k3d-victoriametrics2
          env: dev
        inlineScrapeConfig:
    vmalert:
      enabled: false
    grafana:
      enabled: true
      annotations:
        reloader.stakater.com/auto: "true"
      ingress:
        hosts:
        - grafana.example.com
      sidecar:
        dashboards:
          provider:
            foldersFromFilesStructure: true
      additionalDataSources:
        - name: vm-dev
          type: prometheus
          url: http://vmselect-victoria-metrics-k8s-stack.monitor-system.svc:8481/select/110/prometheus
          access: proxy
          isDefault: false
          jsonData: {}
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - .: &provider
              name: &name Default
              orgId: 1
              folder: *name
              folderUid: *name
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
                foldersFromFilesStructure: false
            - <: *provider
              name: &name Playground
              folder: *name
              folderUid: *name
              options:
                path: /tmp/dashboards/playground
      grafana.ini:
        server:
          root_url: https://grafana.example.com
        users:
          auto_assign_org_role: Editor
          viewers_can_edit: true
        auth.google:
          enabled: true
          client_id: 
          client_secret: 
          scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
          auth_url: https://accounts.google.com/o/oauth2/auth
          token_url: https://accounts.google.com/o/oauth2/token
          allowed_domains: example.com
          allow_sign_up: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitor-system
spec:
  values:
    ingress:
      hosts:
        - host: blackbox.qa.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    config:
      modules: {}
