apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/victoriametrics
  - vmalerts
  - vmrules
  - vmstaticscrape-kafka.yaml
  - vmstaticscrape-vm-node-exporter.yaml
patchesStrategicMerge:
  - helmrelease.yaml