apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: all-pod
  namespace: monitor-system
spec:
  podMetricsEndpoints:
    - scheme: http
      relabelConfigs:
        - action: keep_if_equal
          source_labels: 
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            - __meta_kubernetes_pod_container_port_number
        - action: drop
          source_labels: 
            - __meta_kubernetes_pod_container_init
          regex: "true"
        - sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          action: keep
          regex: "true"
        - sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          action: replace
          targetLabel: __scheme__
          regex: (https?)
        - sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - sourceLabels:
            - __meta_kubernetes_pod_label_app
          action: replace
          targetLabel: app
          regex: (.+)
        - sourceLabels:
            - __meta_kubernetes_pod_label_owners
          action: replace
          targetLabel: owners
          regex: (.+)
  selector: {}
  namespaceSelector:
    any: true