apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: alertmanager
  namespace: monitor-system
spec:
  # Add fields here
  replicaCount: 1
  configNamespaceSelector: {}
  configSelector: {}
  disableNamespaceMatcher: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  # configSecret: alertmanager-config
  configRawYaml: |
        global:
          resolve_timeout: 5m
        route:
          group_by: ['alertgroup','job']
          group_wait: 30s
          group_interval: 2m
          repeat_interval: 30m
          receiver: 'default-receiver'
        receivers:
          - name: default-receiver
            # webhook_configs:
              # - url: http://prometheusalert/prometheusalert?type=fs&tpl=prometheus-fs&split=true&fsurl=
        inhibit_rules:
          - source_match:
              severity: 'critical'
            target_match:
              severity: 'warning'
            equal: ['alertname','alertgroup','instance','app']
