apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitor-system
spec:
  releaseName: alertmanager
  chart:
    spec:
      chart: alertmanager
      version: "0.19.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values: 
    service:
      type: ClusterIP
      port: 9093
      clusterPort: 9093
    ingress:
      enabled: true
      hosts:
        - host: alertmanager.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    config:
      receivers:
        - name: blackhole
        - name: prometheusalert
          webhook_configs:
          - url: http://prometheusalert/prometheusalert?type=fs&tpl=prometheus-fs&split=true

      route:
        group_by:
         - job
         - alertgroup
        group_wait: 2m
        group_interval: 2m
        repeat_interval: 30m
        receiver: blackhole
        routes:
          - matchers:
            - severity=~"warning|critical"
            - env="qa"
            group_by: 
            - job
            - alertgroup
            receiver: prometheusalert
    configmapReload:
      ## If false, the configmap-reload container will not be deployed
      ##
      enabled: true

      ## configmap-reload container name
      ##
      name: configmap-reload

      ## configmap-reload container image
      ##
      image:
        repository: jimmidyson/configmap-reload
        tag: v0.5.0
        pullPolicy: IfNotPresent