apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: dev
  namespace: monitor-system
spec:
  route:
    receiver: default-receiver
    group_interval: 5m
    repeat_interval: 24h
    routes:
      - matchers:
        - severity=~"info|warning|p1|p2"
        - env="dev"
        group_by: 
        - job
        - alertgroup
        repeat_interval: 48h
        receiver: prometheusalerts-nonprod-p2
      - matchers:
        - severity=~"p0|critical"
        - env="dev"
        group_by: 
        - job
        - alertgroup
        receiver: prometheusalerts-nonprod-p1
  receivers:
    - name: default-receiver
    - name: prometheusalerts-nonprod-p1
      webhook_configs:
      - url: http://prometheusalert/prometheusalert?type=fs&tpl=prometheus-fs&split=true&fsurl=
    - name: prometheusalerts-nonprod-p2
      webhook_configs:
      - url: http://prometheusalert/prometheusalert?type=fs&tpl=prometheus-fs&split=true&fsurl=